# Generated by Django 6.0.6 on 2026-07-02 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(unique=True)),
                ('content_raw', models.TextField()),
                ('cleaned_summary', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='General Tech', max_length=100)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tech_articles',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['source_url'], name='tech_articl_source__58e8ed_idx'), models.Index(fields=['fetched_at'], name='tech_articl_fetched_2be1a2_idx')],
            },
        ),
    ]
